### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by MTonyM** [oliverzh2000/audio-networking#1]
Hi, I am interested in your project, Can you tell me how to use it?

**Comment by oliverzh2000** [comment]
Hi, thank you very much for your interest, and I am sorry for the late reply. 

To use this, you can use a physical male-male 3.5mm audio cable that loops from the speaker output on your computer to your microphone input. The FileTransferProtocol.java's main function is already set up to demonstrate sending a request for a directory and responding to this request. Make sure something is in your server base directory and whatever is in there will be transferred to the client's base directory. 

If you are trying to do this with 2 physical computers, you need to delete the code for server on one computer and client on the other.  Of course, you will need 2 cables to plug into each computer's mic and speaker jacks. 

Again sorry for the late reply, I hope this was some help. Please feel free to reply to me if you have any other questions

**Comment by MTonyM** [comment]
Thank you for your reply. This project is awesome!
